project:
  type: website
  output-dir: docs

website:
  title: "VT0007"
  navbar:
    left:
      - href: VT0007-deforestation-map.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

